### ISSUE TITLE
Forming rectangle from line segments

### ISSUE THREAD

**Issue by wiamadaya** [yanconglin/Deep-Hough-Transform-Line-Priors#1]
Given a list of detected line segments (with start and end points) that are horizontal and vertical, how can I find all the rectangles that they form?

**Comment by yanconglin** [comment]
One simple idea (maybe not the most efficient one): you can simply group all endpoits in a hierachical way, since the connectivity (which line segments intersect at an endpoint) is alreay available. By doing so, you may obtain all possible polygons, then pick up those rectangles from all proposals. Another option would be the HT bin, which give you information about the orientation(orthogonality) of those lines. SInce you have endpoints, so the HT may not be of much help. As I can imagine, there could be many tricks, depending on the task.
