### ISSUE TITLE
Questions about training on new datasets.

### ISSUE THREAD

**Issue by ghost** [yanconglin/Deep-Hough-Transform-Line-Priors#12]
Thanks for your great work!

I use ht-lcnn on my dataset. The results of the default parameters are ok, but the accuracy is still a little worse, so I increased the resolution of the input image and changed the vote_index to 140x140,  180x180 respectively, but the results of these two are far It's not as good as the default 128x128. 

so I want to ask, besides this vote_index that needs to be modified, are there other parameters that need to be changed? What other parameters should I change if I want to get better results on my dataset?

Look forward to your reply.

**Comment by yanconglin** [comment]
em,  I do not think there are other parameters to change.  I can't say much about the performance without seeing any results or knowing your dataset. Be aware that the LCNN style model is composed of multiple parts, including junction+line vectorization. In my experience, these are the main bottleneck for further improvement. We need these because HT does not give endpoints. So it is hard to tell whether HT  or the  junction+line vectorization is not working

**Comment by ghost** [comment]
thanks for your reply, I will seriously think about it
